spring:
  jpa:
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled : true
    remote :
      restart:
        enabled : false
  thymeleaf:
    cache: false


